apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-webapp
  labels:
    app: mnist-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-webapp
  template:
    metadata:
      labels:
        app: mnist-webapp
    spec:
      imagePullSecrets:
      - name: my-secret
      containers:
      - name: webapp
        image: ghcr.io/bmppa/mnist_webapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-webapp-service
  labels:
    app: mnist-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: mnist-webapp